name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DROPLET_SSH_KEY }}
        name: deploy_key
        known_hosts: github.com,170.64.162.86
    
    - name: Setup SSH Config
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/config << EOL
        Host github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/deploy_key
        Host ${{ secrets.DROPLET_HOST }}
            HostName ${{ secrets.DROPLET_HOST }}
            User ${{ secrets.DROPLET_USERNAME }}
            IdentityFile ~/.ssh/deploy_key
        EOL
        chmod 600 ~/.ssh/config
    
    - name: Debug SSH Setup
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/config
        ssh -v ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} echo "SSH connection test"
    
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /home/deployer/financial_score
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          pkill gunicorn
          gunicorn -c gunicorn_config.py app:app > gunicorn.log 2>&1 & 